
[tool.black]
line-length = 79
[tool.poetry]
name = "opal"
version = "0.1.0"
description = ""
authors = ["Evening <dev_evening@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.9.7 || >3.9.7"
torch = "^2.2.1"
torchaudio = "^2.2.1"
torchvision = "^0.17.1"
pytorch-lightning = "^2.2.1"

[tool.poetry.group.dev.dependencies]
plotly = "^5.20.0"
scikit-learn = "^1.4.1.post1"
wandb = "^0.16.4"
streamlit = "^1.32.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
